### ISSUE TITLE
Shadow on fulll effect area

### ISSUE THREAD

**Issue by IIopn** [sabresaurus/SabreCSG#10]
A shadow could appear on a full effect area.
![bug1_sabrecsg](https://cloud.githubusercontent.com/assets/18546079/25758559/35209790-31f9-11e7-8d0b-1a53d9db4cf3.PNG)

This could be fixed by enabling the Shadow area to be Two-Sided, but changing it manually would be quite a hassle.

An option to choose the Shadow Type of the Mesh would be wonderful.

**Comment by sabresaurus** [comment]
Shadow casting mode can now be set on CSG Models, see https://github.com/sabresaurus/SabreCSG/commit/17e9aef66c1897d4bcbde780d310eed57f655f3e
