### ISSUE TITLE
Screen.safeArea missing on import.

### ISSUE THREAD

**Issue by Siccity** [sabresaurus/SabreCSG#126]
Unity version: 2017.2.0f3
![image](https://user-images.githubusercontent.com/6402525/40589988-a234a3ba-61f7-11e8-9d79-66abf99c0b08.png)

**Comment by sabresaurus** [comment]
@Henry00IS Looks like safeArea was introduced in 2017.2.1 - http://sabresaurus.com/unity-api-versioner/?api=safeArea

**Comment by Henry00IS** [comment]
I will fix this first thing in the morning, I don't want to rush it at 12:34 AM.

**Comment by Henry00IS** [comment]
Thanks for the detailed report @Siccity and for the ifdef listing @sabresaurus!
Problem has been solved and tested with 2017.2.0f3.
