### ISSUE TITLE
ResizeEditor.cs -- The name `targetBrushBases' does not exist in the current context

### ISSUE THREAD

**Issue by ambroiseRabier** [sabresaurus/SabreCSG#13]
On a new project using unity 5.6.0f3 import SabreCSG, you will get a ton of error like this one bellow:

Assets/SabreCSG/Scripts/Tools/ResizeEditor.cs(1539,55): error CS0103: The name `targetBrushBases' does not exist in the current context

**Comment by sabresaurus** [comment]
Sounds like it may have been a bad import, I'd suggest downloading a zip from this repo again and importing into a fresh project. I've just tried that and it imports correctly without warnings/errors and lets me create a CSG model

**Comment by ambroiseRabier** [comment]
It work whit a new project and by redownloading the zip, i don't know what did go wrong. Thanks.
