### ISSUE TITLE
Bug: Mesh in subtract brush near stairs

### ISSUE THREAD

**Issue by Siccity** [sabresaurus/SabreCSG#130]
I'm really loving the asset. CSG is amazing to work with. But sometimes it just doesn't want to cooporate. I'm trying to add stairs next to this door, but it screws up the mesh.
![2018-05-29_21-27-39](https://user-images.githubusercontent.com/6402525/40680686-46ea8b14-6387-11e8-80b5-0696671b745d.gif)

**Comment by Henry00IS** [comment]
Try disabling "Optimize Geometry" in the CSG Model settings. That will probably fix it.

**Comment by Constaneer** [comment]
That happens with normal cubes is well
