### ISSUE TITLE
Unity3d mesh to SabreCSG and vice-versa

### ISSUE THREAD

**Issue by saravanan2020** [sabresaurus/SabreCSG#137]
Hi, is there a way to load unity gameobject mesh to SabreCSG brush object and doing needed operations and store back to unity gameobject's mesh?

**Comment by saravanan2020** [comment]
I will try it.

**Comment by saravanan2020** [comment]
Shall i make it runtime and add it as a part of SabreCSG? May it be my contribution to your tool?.

**Comment by Henry00IS** [comment]
I am not sure what you mean, what are you going to make runtime?
There is a Runtime CSG API (you can enable it in the preferences window).

**Comment by saravanan2020** [comment]
Yes, Ok i will make it runtime and will give my contribution. Will get back to you. Bye.

**Comment by Henry00IS** [comment]
It's been nearly half a year. I am going to assume this issue can be closed. Especially because our current convex brush limitation makes the use cases for this feature very limited. If you did end up creating something feel free to open a pull request! :)
