### ISSUE TITLE
Compiler error in Unity 2017.1.0f3

### ISSUE THREAD

**Issue by andybak** [sabresaurus/SabreCSG#14]
Assets/SabreCSG-master/Scripts/Core/CSG/Polygon.cs(168,36): error CS0029: Cannot implicitly convert type `void' to `UnityEngine.Plane?'

I'd guess that:

    cachedPlane = cachedPlane.Value.Flip();

could just be:

    cachedPlane.Value.Flip();

**Comment by sabresaurus** [comment]
Thanks, just pushed a fix for 2017.1 and above

**Comment by pedro15** [comment]
I'm using sabre csg with unity 2017 and the real fix is : 
`cachedPlane = cachedPlane.Value.flipped;`

**Comment by sabresaurus** [comment]
Good point, pushed the change to apply the flipped copy properly
