### ISSUE TITLE
Vertex editor: vertices not recognized as edges

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#159]
If you select the vertices of an edge the edge options will remain disabled. This makes marquee selects useless for edges as well.

![image](https://user-images.githubusercontent.com/7905726/42082811-46f2cb52-7b89-11e8-94fa-908456113b14.png)

**Comment by PatrikSakac** [comment]
I´ve started to work on this issue. I will create pull request soon. It will include selecting of edges when you select area of a rectangle. It should solve your problem.

**Comment by Henry00IS** [comment]
Fixed in #171.
