### ISSUE TITLE
Mesh problems caused by Boolean operations

### ISSUE THREAD

**Issue by NeverMore-Father** [sabresaurus/SabreCSG#176]
version：1.7.2
Runtime mode

![tim 20181102095400](https://user-images.githubusercontent.com/36830623/47889504-4dacff80-de85-11e8-833e-bfe56ddd0b79.png)

![1541123656 1](https://user-images.githubusercontent.com/36830623/47889511-56053a80-de85-11e8-92c2-faee38c2d174.jpg)
I created three cubes like this。
I want to dig a hole in the front and back of a big cube。
But there seems to be something wrong with the front.It looks dark.
And then I tested all the data on the mesh triangle.
![tim 20181102100306](https://user-images.githubusercontent.com/36830623/47889779-ab8e1700-de86-11e8-9475-34b90a21cd50.png)
![tim 20181102100356](https://user-images.githubusercontent.com/36830623/47889794-b8126f80-de86-11e8-9e6f-072fc47fdc11.png)

The point order of the triangle is correct，But the normal line is reversed.

At first, I thought it was my code.

But when I grew the sides of the cuboid, it was all normal.

I look forward to your help.

**Comment by Kerfuffles** [comment]
[We just released V1.8.0](https://github.com/sabresaurus/SabreCSG/releases/tag/v1.8.0). Please try that release and let us know if that fixed your problem.

If not, then the best advice I can give you is to try `Force Rebuild` if you have not, and then making sure that brushes align to the grid. There is a known issue right now with floating point precision that we can't exactly fix just yet (but it's on the to-do list).

**Comment by Henry00IS** [comment]
Also make sure "Optimize Geometry" is off in your CSG Model settings. That's off by default in more recent versions of SabreCSG as it has a couple bugs.

**Comment by Henry00IS** [comment]
After staring at this issue for ages I noticed your brush is very small:

![a](https://user-images.githubusercontent.com/36830623/47889511-56053a80-de85-11e8-92c2-faee38c2d174.jpg)

Values of 0.036 are close to some of our epsilon values to deal with floating point precision errors. I wouldn't use subtractive brushes at this scale, use 4 additive brushes to create your shape instead.

**Comment by Henry00IS** [comment]
Same issue as #163 and #8 and can't can't be fixed until we switch to fixed point mathematics.

**Comment by NeverMore-Father** [comment]
Thank you for your answer。
![tim 20181106091332](https://user-images.githubusercontent.com/36830623/48036666-5adb2e80-e1a4-11e8-89fd-69ef2a279b30.png)
10/5000  
I want to make a Roman column like that
if i make it with some additive brushes will more than 5 
Because it's not just one side that needs digging，Even each side needs more than one dong
