### ISSUE TITLE
 Light and Shadow Effect

### ISSUE THREAD

**Issue by LeansYouriy** [sabresaurus/SabreCSG#196]
Unity 2017.4.3f1, SabreCSG 1.7.2.

I created a new scene and created a cube with the UnityEdtior tool to give the SabreCSG default material;

![e da grrj0 hki18 xmib](https://user-images.githubusercontent.com/33061113/49933195-f7ac8c80-ff05-11e8-8ad0-ae42f7bedf1c.png)

After run I got this effect.
![5hedvz e6ckv2 as m_n mc](https://user-images.githubusercontent.com/33061113/49933334-4fe38e80-ff06-11e8-96d0-98b06a90afc4.png)

But I use the same scene and created a cube with SabreCSG, but I got this effect, 
![image](https://user-images.githubusercontent.com/33061113/49933476-b1a3f880-ff06-11e8-99ae-9ce337a18bb2.png)
![image](https://user-images.githubusercontent.com/33061113/49933520-cb454000-ff06-11e8-8ba2-b050f117676c.png)

I am confused about this, because I didn't find the lighting settings in the two scenes and the material shader of the cube. However, the gap between light and shadow is so great, and scenes created using SabreCSG have not been able to restore Unity's default scene lighting effects even after removing SabreCSG-related objects. I hope to use SabreCSG to create objects but get the default lighting effects with UnityEditor, please help me.

**Comment by Henry00IS** [comment]
This isn't necessarily SabreCSG exclusive, open up the "Window -> Lighting -> Settings" window and press the generate lighting button:

![image](https://user-images.githubusercontent.com/7905726/49934053-a1bbf280-fecd-11e8-8f1d-6cf01b0dc385.png)

The problem is that it doesn't have any reflection probes so reflections don't work, so it just defaults to black and darkness.

**Comment by LeansYouriy** [comment]
Thank you, It works for me! But I have another question, I used the SabreCSG code to dynamically create some objects, and the reflections of those objects  doesn't work in runtime. Does the Unity engine have no way to perform the same light reflection calculation  as baking in runtime ?

**Comment by vertxxyz** [comment]
Dynamic objects have their reflections calculated using Reflection Probes.
https://docs.unity3d.com/Manual/UsingReflectionProbes.html
https://docs.unity3d.com/Manual/class-ReflectionProbe.html
Objects also need to be tagged appropriately as static to render into the probes.

And their lighting often calculated with Light Probes.
https://docs.unity3d.com/Manual/LightProbes.html
https://unity3d.com/learn/tutorials/topics/graphics/probe-lighting?playlist=17102
Which bake lighting information into 3D space.

Realtime shadows can apply shadows on top of both of these.

The details of all the above can also depend on what render path or scriptable render pipeline you are using.

**Comment by Henry00IS** [comment]
Can this issue be closed? 😀

**Comment by LeansYouriy** [comment]
Yes! 😀
