### ISSUE TITLE
Support for EditorXR

### ISSUE THREAD

**Issue by andybak** [sabresaurus/SabreCSG#20]
...would be astonishing.

However I'm sure it's not trivial. I thought it would be worth leaving this here as a placeholder as I'm not going to be the only person dreaming of level design with a headset on.

I'm going to wait for a few more examples of custom additions to EditorXR to surface to see how complex it is to add in support. So far I've only found two (neither of which are actively being updated):

https://github.com/ajcampbell1333/unity3d-editorvr-hierarchymode

https://github.com/peteyhayman/Zodiac

**Comment by sabresaurus** [comment]
Unfortunately not something that I can take on as it would be a huge amount of work and I don't own any VR equipment, supporting VR/AR would require such divergence from this codebase that it would make more sense as its own repo. I'm happy to leave this issue open in case it inspires someone.

**Comment by sabresaurus** [comment]
Going to close this issue as VR/AR support is not currently in the roadmap.
