### ISSUE TITLE
License question about integration into the game

### ISSUE THREAD

**Issue by pointcache** [sabresaurus/SabreCSG#21]
Hi im making a tycoon game where currently im using sabre to dynamically build walls on runtime
![image](https://user-images.githubusercontent.com/5315202/33966589-068a4aaa-e015-11e7-93f0-c2b8a0c92208.png)

Since we have planned asset editor for the game (buildings, props, cars..) is it possible to integrate sabre toolset for runtime use in asset editor in game? I'm asking - does license allow me this?

**Comment by RobbyZ** [comment]
I am not a lawyer, but my understanding is that as long as you provide proper attribution of the library in your credits or other appropriate location you would be okay.  Please see the project's MIT License [here](https://github.com/sabresaurus/SabreCSG/blob/master/LICENSE) -- it is generally considered a safe license for integrating into commercial projects with many popular libraries/addons using it.

Recommend closing this issue.

**Comment by sabresaurus** [comment]
As @RobbyZ says the license allows that.
