### ISSUE TITLE
Support for heavily scaled brushes.

### ISSUE THREAD

**Issue by Siccity** [sabresaurus/SabreCSG#23]
I'm trying to import a level from another engine that uses CSG. The imported brushes are scaled, rotated and pivoted to oblivion (including root CSGModel). Support for this would be fantastic.

**Comment by sabresaurus** [comment]
Which engine are you trying to import from

**Comment by Siccity** [comment]
I was trying to import a .t3d file which was extracted from UnrealEd 1. Because of this i was setting up the CSG hierarchy from my own code instead of SabreCSG editor. The result was a lot of heavily scaled brushes. Even the root was scaled. I fixed the issues on my own by applying scale to the meshes individually, but you still might want to check root scale if anyone else should bump into the same issue.

**Comment by Henry00IS** [comment]
You can also make all brush transformations permanent in UnrealEd before exporting instead. Are you using 227? 👍
