### ISSUE TITLE
[2019.2.5f1] SabreCSG meshes not receiving realtime lighting properly

### ISSUE THREAD

**Issue by JillCrungus** [sabresaurus/SabreCSG#239]
I have no idea what's causing this but SabreCSG meshes in my project aren't at properly receiving realtime lighting. Baked lighting works but takes a long time to bake even for a simple scene. Unity's standard primitives are receiving lighting just fine. But SabreCSG meshes aren't.

It's that that they aren't receiving the lighting at all - they are, and I can see it if I crank up the light intensity to ludicrous levels. I have no idea what could be causing it.

I've attached a zip containing 2 videos. The first shows that Unity's primitive meshes are receiving lighting properly, the second shows the SabreCSG meshes _are_ receiving the lighting, but not properly.

[Vids.zip](https://github.com/sabresaurus/SabreCSG/files/3898872/Vids.zip)

I don't know if this is an issue with my lighting settings or what, or if there's any way I could reset them to the defaults. I've fiddled with them a bunch but not had any success in fixing the issue.

**Comment by Henry00IS** [comment]
Hey Jill, just for reference, what Unity version are you using?

**Comment by JillCrungus** [comment]
> Hey Jill, just for reference, what Unity version are you using?

As stated in the issue title, 2019.2.5f1.

It's more than likely that this may be a problem with my settings for the project but I'm not sure what specifically could be causing it.

**Comment by JillCrungus** [comment]
Well I've made a new project and it's working fine there so obviously something's went very wrong with my lighting settings.

**Comment by Henry00IS** [comment]
Yeah I can also confirm that it works fine... well I believe SabreCSG does mess with the "Auto Generate" checkbox in the lighting settings. #230

**Comment by JillCrungus** [comment]
As is typical, I've found the issue immediately after seeking help for it. Turns out that at some point I'd accidentally managed to knock the pixel light count in the quality settings to 0, which apparently causes this issue. 

This is concerning though, because it means that any game that uses Unity's default quality settings and SabreCSG will have realtime lighting break on quality settings below "Medium", which sets the pixel light count to 0.

**Comment by Henry00IS** [comment]
I have been able to reproduce the issue by reducing the quality settings to medium indeed. It appears that Unity falls back to a simple per-vertex lighting scheme. Having a small default box or plane receives lighting however making them larger yields identical results:

![image](https://user-images.githubusercontent.com/7905726/69762170-b8ed0200-1169-11ea-898e-dc36c09ff626.png)

Unless you move the light closer to a vertex:

![image](https://user-images.githubusercontent.com/7905726/69762212-d91cc100-1169-11ea-81cb-33052a1c773f.png)

Same with SabreCSG meshes:

![image](https://user-images.githubusercontent.com/7905726/69762251-f8b3e980-1169-11ea-80f9-8dcd49d61b75.png)

Unless you move the light closer to a vertex:

![image](https://user-images.githubusercontent.com/7905726/69762276-0ec1aa00-116a-11ea-9652-c0aa7cd67296.png)

As such it doesn't matter whether you use SabreCSG or any other mesh and I believe it's out of the scope of this project to fix it. It should be up to the game developer.

**Comment by Henry00IS** [comment]
I assume that this issue has been resolved and I will close it as no reply has been posted for almost a month. You can re-open this- or create another issue if you find that this is a problem with the mesh output of (or exclusively with) SabreCSG, which does not seem to be the case.
