### ISSUE TITLE
Selection Helpers dropdown doesn't appear in 2019.3

### ISSUE THREAD

**Issue by vanjac** [sabresaurus/SabreCSG#242]
The Selection Helpers dropdown isn't visible at all in the face UI.

![image](https://user-images.githubusercontent.com/8228102/71348185-db7ffa00-2520-11ea-9c5b-be614036405e.png)

**Comment by Henry00IS** [comment]
Thanks for the report! While some backgrounds (mainly the toolbar at the bottom) are still transparent at least every feature should be accessible now.
