### ISSUE TITLE
Marking generated meshes as static by default

### ISSUE THREAD

**Issue by ssoher** [sabresaurus/SabreCSG#268]
Is there an option to mark generated meshes as static by default? Right now I have to do that manually after every rebuild.

**Comment by Henry00IS** [comment]
I can't reproduce this problem. If you set the CSG Model and its children to static (and optionally tick the "Generate Lightmap UVs" option) it never changes, even with new meshes due to additional materials.

**Comment by ssoher** [comment]
ah, didn't know the generated mesh inherited the static settings from the CSGModel parent, yes it works this way, thanks!
