### ISSUE TITLE
[FEATURE REQUEST] Add runtime mode tools

### ISSUE THREAD

**Issue by darkhog** [sabresaurus/SabreCSG#3]
I know there's a code API to make levels at runtime, but I suck at making things like handles for vertices, etc.

I'd like to request a 1:1 equivalent of SabreCSG tools that work at runtime (without Unity). My reasoning is that I want to add extensive level editing to my game. Thing that I have now works, but it isn't too good. I want players to make levels without the need to fight with assetbundles and so on, directly in the game. Therefore, runtime version of SabreCSG would greatly help achieve this.

Ability to serialize/deserialize resulting level data into arrays of basic types, so they can be then stored as part of custom binary data format I've developed for my game would be welcome.

Note that I am unable to do such port myself, otherwise I'd be doing it right now instead of talking.

**Comment by andybak** [comment]
I had an overlapping but maybe simpler requirement.

I wanted to animate brushes and have the resulting mesh update. Is there already a way to achieve this? It would go some of the way to addressing the functionality @darkhog is requesting.

**Comment by sabresaurus** [comment]
@darkhog Unfortunately runtime support is something which never left the experimental stage and as most users use SabreCSG as an in-editor level design tool that's where I'm focussing the limited amount of time I have for SabreCSG development. Sorry I can't be of help in this case.

@darkhog This is technically possible with the existing runtime support for SabreCSG, I would suggest starting with the [docs here](http://sabrecsg.com/learn/docs/), depending on complexity you could call Rebuild() each frame.

**Comment by sabresaurus** [comment]
Going to close this issue as it's not something I personally can work on, but if you do work on this a pull request is very welcome! :)
