### ISSUE TITLE
Support for Vertex Snapping

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#32]
Whenever I have edge cases (get it?) like this:

![image](https://user-images.githubusercontent.com/7905726/35685314-a6693920-0769-11e8-8967-b8a7c41e6774.png)

I wish I could just use the same vertex snapping Unity provides while holding V. It would be a miracle and make the workflow so much easier. Is it possible to add support for this?

**Comment by vertxxyz** [comment]
I'm pretty certain you can vertex snap in vertex mode (I've just tested it in an older version)
It would be cool if a lot more functions had it and it was better than Unity's snap (which isn't that great) but the basic support should be there already.

**Comment by Henry00IS** [comment]
You can snap individual vertices whenever the translate gizmo appears on them true, but not the entire object on any vertex like in Unity while holding V. This is what I would like to see in bounds or translate mode or alike:

![snapp](https://user-images.githubusercontent.com/7905726/35720083-87782aac-07ec-11e8-8fe2-5c782ea1642e.gif)

**Comment by Henry00IS** [comment]
Hmm but you are right. I could recycle the code of the vertex editor and simply have a translate gizmo appear when you hover close to a vertex.
