### ISSUE TITLE
Shouldn't compound brush variables be public for Runtime CSG?

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#41]
I have never tried using the Runtime CSG library before but one thing that always seemed odd is that we made all of the compound brush variables private like this:

```C#
        [SerializeField]
        float stepDepth = 0.2f;
        [SerializeField]
	float stepHeight = 0.1f;
        [SerializeField]
        float stepDepthSpacing = 0f;
        [SerializeField]
        float stepHeightSpacing = 0f;
        ...
```
Doesn't that make it extremely difficult if not nearly impossible to use compound brushes?
Should we make them public or add properties for them?

**Comment by sabresaurus** [comment]
PrimitiveBrush fields also are private, but yes we should add properties for them. I'm not a fan of making fields public except in data only classes as the interface and implementation should be kept separated. For example we may later decide that when another class sets stepHeightSpacing we want some code to run.
