### ISSUE TITLE
[Request] Translate selected vertices pivoted to a single vertex

### ISSUE THREAD

**Issue by Chabinka** [sabresaurus/SabreCSG#44]
https://imgur.com/VFMQHJt

Would this be possible to implement?  It's something I used often with Valve's Hammer Editor, it can be really useful at times.

**Comment by Henry00IS** [comment]
Great idea! This [new behavior](https://github.com/sabresaurus/SabreCSG/pull/63) makes it much easier and more precise to use the vertex editor!

**Comment by Chabinka** [comment]
Awesome!  I gave it a whirl but one small problem, if you rotate a brush then try to translate by a vertex, it remains slightly offset from the grid.

Example: https://i.imgur.com/p8mcOh1.gifv

Is there a way to line it up to the grid without affecting its shape?

**Comment by Henry00IS** [comment]
Well this is not because of my changes. It was always this way. Press the "Global Snap" button if you wish to snap it to the grid again.

**Comment by Henry00IS** [comment]
Ah sorry I didn't read the entire thing thoroughly. There is no way currently to snap it to the grid... but in translate mode you can hold the V key down and use vertex snapping to place it correctly against another brush. Which may do the job?

**Comment by Chabinka** [comment]
Ah yep that will work for what I need.  The new vertex tool will be very useful too.  Thanks for the updates :)
