### ISSUE TITLE
🎥 Please contribute a SabreCSG 2D Shape Editor tutorial video!

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#48]
If you wish to contribute a **SabreCSG 2D Shape Editor Tutorial** please do so and post a link to the YouTube video in this issue! We will [feature it in the wiki](https://github.com/sabresaurus/SabreCSG/wiki/Video-Tutorials) in several places for all to see.

Here are some suggestions that could be covered in the tutorial:

- How to create shapes using [segments](https://github.com/sabresaurus/SabreCSG/wiki/2D-Shape-Editor#arch-example) and [bezier curves](https://github.com/sabresaurus/SabreCSG/wiki/2D-Shape-Editor#bezier-curves).
- A couple [extrude modes](https://github.com/sabresaurus/SabreCSG/wiki/2D-Shape-Editor#create-polygon) if not just all of them.
- Saving and loading files, [loading embedded projects](https://github.com/sabresaurus/SabreCSG/wiki/2D-Shape-Editor#embedded-projects).
- Practical [usage examples](http://htmlpreview.github.io/?https://raw.githubusercontent.com/wiki/sabresaurus/SabreCSG/websites/unrealism/Unreal%20Editor%20Maximum%20%5Bunrealism.com_unrealedmax%5D%20-%202D%20EDITOR%20SHAPES.html "See bottom of page for some ideas") while designing levels with the 2D Shape Editor.

This is just a suggestion, feel free to do what you think is best. If you wish to make a small series, go ahead. As we sadly don't get paid I don't have the right to tell you what to do anyway.

You can use [this wiki page](https://github.com/sabresaurus/SabreCSG/wiki/2D-Shape-Editor) for more information.

To anyone interested, thank you so much, I can't wait to see what you come up with! :)
If you have any questions please feel free to ask me here.

**Comment by JudgeGroovyman** [comment]
https://youtu.be/4gyiELf4-N4

Hey I hope this helps.  I touched on the first three bullets.  I can still make some minor edits without too much trouble.

**Comment by Henry00IS** [comment]
That tutorial video is very nice! Thank you so much for taking the time to do this! Like you pointed out in the video some of those features truly make us stand out from the rest of the competition. I hope more people get interested in trying out SabreCSG.

I am going to keep this issue open for a while longer in case anyone else was working in parallel. But I am definitely going to place this tutorial in the wiki and spam it on social media. 😁
