### ISSUE TITLE
Persisting built geometry including texture/material

### ISSUE THREAD

**Issue by Alx101** [sabresaurus/SabreCSG#5]
I've been looking around, but can't find anything on the topic. 
I need to be able to store a SabreCSG model to be loaded in at runtime (level instansing and such). 
I know there is a way to build the geometry built in SabreCSG into a .obj file, however this strips away any textures previously applied to the model. 
I have tried to create a prefab with the SabreCSG model in it, but whenever I pull it into a scene the model needs to be re-built. This is an issue since there is no run-time brush-building from what I've gathered. It also breaks any prefab instance, meaning that if I later update the prefab it will not reflect in the scene. Is there a way for us to be able to persist the full SabreCSG model including textures other than keeping it stored in a scene and loading that in?

Thanks!

**Comment by sabresaurus** [comment]
The reason for this behaviour is that there are two ways to store a generated mesh asset - implicitly by just generating a mesh in a scene (these kind of assets are stored in the scene file), or explicitly by generating a .asset file on disk (allowing the mesh asset to be referenced by a prefab or other scenes). Right now SabreCSG only supports mesh assets that are part of the scene, but I'll take a look at what's required to add a mesh asset option.

**Comment by Alx101** [comment]
Okay! I'd be happy to help if necessary/wanted. A second follow up question: is it possible to export UV'S and textures/materials alongside the .obj export?

**Comment by sabresaurus** [comment]
The OBJ exporter should export the primary UVs correctly, but does not export textures or materials as that's something I've never got around to adding. If you wanted to add that support it would be very much appreciated!

**Comment by sabresaurus** [comment]
Had a quick look at this issue and I've added an experimental option for it - see https://github.com/sabresaurus/SabreCSG/commit/b2a6b8f709a194bdeb8ae55a894da411b9a568e9

**Comment by Alx101** [comment]
Thank you for speedy response! I'll try it out later today. 
I'd love to give material/texture exporting a go, could you perhaps point me in the right direction where to look in the code, and I'll see what I can conjure up!

**Comment by sabresaurus** [comment]
Sure, so the main class that handles exporting OBJs in SabreCSG is the
OBJFactory
<https://github.com/sabresaurus/SabreCSG/blob/master/Scripts/Geometry/OBJFactory.cs>

From memory, in addition to the OBJ file we need to export an MTL file
which holds the materials, references to the materials should then be
hooked up in the OBJ using the 'usemtl' command.

There's actually quite a good spec for it on Wikipedia -
https://en.wikipedia.org/wiki/Wavefront_.obj_file



Barnaby Smith
Director | Sabresaurus Ltd. <http://sabresaurus.com>

<http://sabresaurus.com/>
Follow Sabresaurus on Twitter <https://twitter.com/sabresaurus>

**Comment by Alx101** [comment]
Hmm. I'm getting some errors with building that last commit. I'm on  5.5.1f and it complains that the "EditorSceneManager.EnsureUntitledSceneHasBeenSaved(string) is inaccessible due to its protection level". 

Sorry for the confusion, I was referring to saving the textures/materials as a unity material file that can just be pulled onto the meshrenderer, although I think I'll give the MTL export a shot!
