### ISSUE TITLE
[Suggestion] Add ability to clip corners

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#52]
The current clip tool can only cut on two axis:

![Showing the current clipping angles](https://user-images.githubusercontent.com/7905726/37275566-e1d7cbc2-25df-11e8-979b-2bdb346c5f0e.png)

It would be nice of the user could manipulate the blue handle to cut corners off of brushes:

![Showing a new corner clipping angle](https://user-images.githubusercontent.com/7905726/37275593-f763d99a-25df-11e8-9549-4a78bba20d44.png)

**Comment by vertxxyz** [comment]
If you click on a handle for you can move the plane to cut any angle. It
could be more intuitive and control focus a little stronger though.

**Comment by Henry00IS** [comment]
... that is absolutely brilliant, I always tried to drag the blue cursor and instead of it moving it would just make an entirely new clip instead. You are so right, you can just click on them once to manipulate them! Thank you! Yes this really should be more intuitive, I am just so glad this feature already exists because the math involved would have been a nightmare to figure out.

**Comment by Henry00IS** [comment]
I added an [entry to the wiki](https://github.com/sabresaurus/SabreCSG/wiki/Brush-Tools-Clip#precision) so that this feature is at least mentioned somewhere. By selecting points you can even use vertex snapping to align your clipping planes, a feature I desperately wanted to have!

Since it's technically not broken I won't change the behavior, but perhaps in the near future we should overhaul the UI and tools to provide context-sensitive instructions, tooltips and wiki links to inform the user how to do certain operations including things that may only be accessible using the keyboard.

Thanks again Thomas!
