### ISSUE TITLE
Extrude Face puts the face in the wrong place when 2D Shape Editor Brushes not at origin

### ISSUE THREAD

**Issue by JudgeGroovyman** [sabresaurus/SabreCSG#55]
Heres a 30second video showing the problem (its easy for me to reproduce)
http://somup.com/cFe2fpVBu1  
( its unlisted so anyone who has the link can see it but it won't be in the youtube search results) 

Briefly summarizing the video: When I do the "extrude face" function it works on default cubes, but trying to extrude face on a shape made by the 2d shape editor has a problem: the extruded face is placed near the origin and not on the original face where it should be.

The problem seems to only happens if the Shape Editor Brush is not located at 0,0,0
Heres another video showing me narrowing down the problem space 
http://somup.com/cFe2f8VBui

How can I help?

**Comment by Henry00IS** [comment]
You helped a lot by providing those videos. I encountered this bug elsewhere with regular brushes but I moved my CSGModel so I figured that was the reason, but now that you pointed that out I managed to fix all of the bugs and issues:

* Fixed the world position of newly extrudes faces (of a compound brush) ending up at 0,0,0.
* It now turns them into regular brushes.
* Fixes brushes ending up at the wrong position when the CSGModel has been moved by the user.

Thanks again! Once [this PR](https://github.com/sabresaurus/SabreCSG/pull/56) is merged this issue will be closed!
