### ISSUE TITLE
Built CSG Model Disappearing

### ISSUE THREAD

**Issue by gildedhipbone** [sabresaurus/SabreCSG#57]
First off, this issue only occurs when the user is being a bit daft. However, it still may happen in the rush of editing and could ruin an entire CSG model.

This is how I've been re-created the problem. Draw a shape on a surface without extruding it.
![layer 4](https://user-images.githubusercontent.com/36510916/37400086-038643a2-2784-11e8-9a70-067fa8c153fb.png)
Draw another shape overlapping the first one.
![layer 5](https://user-images.githubusercontent.com/36510916/37400087-03a5579c-2784-11e8-9399-aa7ec9bfc986.png)
Extrude.
![layer 6](https://user-images.githubusercontent.com/36510916/37400089-03c1d444-2784-11e8-869f-a482c7a0279c.png)
The extruded shape isn't converted to level geometry. The following error message pops up:
"Polygon splutting has resulted in two zero area polygons. This is unhandled. UnityEngine.Debug:LogError(Object)"
![layer 7](https://user-images.githubusercontent.com/36510916/37400090-03e5c52a-2784-11e8-8070-b222514e1b19.png)
Realizing one has made a mistake, the natural inclination is to undo the action. This causes the entire CSG model to lose it's level geometry. From this point it's no longer possible to select any of the brushes in the hierarchy.
![layer 8](https://user-images.githubusercontent.com/36510916/37400091-04004ca6-2784-11e8-9745-598a63aca1b4.png)
Re-doing doesn't help.
![layer 9](https://user-images.githubusercontent.com/36510916/37400092-04232c4e-2784-11e8-8f2a-7327162722d8.png)
The only fix I've discovered is to remove the conflicting shape(s) and move the remaining brushes to a new CSG model.

**Comment by Henry00IS** [comment]
Until this issue is fixed, I wish to quickly point out that I found that another way to fix this issue: Simply manually delete the "MeshGroup" object and rebuild.

**Comment by gildedhipbone** [comment]
Confirming that deleting the MeshGroup (after removing the conflicting brush) works. :)
