### ISSUE TITLE
[Request] Group Brushes Using Shortcut + Selection Behavior

### ISSUE THREAD

**Issue by gildedhipbone** [sabresaurus/SabreCSG#58]
It's possible to group brushes by creating an empty GameObject and inserting the brushes as children. Could this be handled automatically? E.g. select the brushes you wish to group, press Ctrl+G and a parent GameObject is created.

Also, it would be convenient if selecting a parent GameOject selected all the children. And/or, if there was a option to select the entire group when clicking a child. Is this feasible? Perhaps it would make more sense to group brushes using some specific Sabre CSG object instead.

**Comment by Henry00IS** [comment]
As for your first question, it already exists, instead of CTRL+G just press the G key. To ungroup, press SHIFT+G. You can see this in the preferences window under key mappings or [in the wiki](https://github.com/sabresaurus/SabreCSG/wiki/Keyboard-Shortcuts).

**Comment by gildedhipbone** [comment]
Well, that's embarrassing. Thank you.

**Comment by Henry00IS** [comment]
I made a blunder just like it [very recently here](https://github.com/sabresaurus/SabreCSG/issues/52) haha. But I like your selection idea, makes a lot of sense. Will see how well it works. 😄

**Comment by Henry00IS** [comment]
I implemented most of your wishes. You can now create a group, remove a group, select all brushes in a group and select the group in the inspector. Sadly selecting the group and moving all brushes at once with the resize tool isn't an option, but you can quickly select every brush in the group now with a single button press and then move them.
We'll have to wait and see what the @sabresaurus thinks.

**Comment by gildedhipbone** [comment]
Wow! Nice work, man. Been trying out the new features for a while and they work great!

I want to preface this by making clear that I'm not a programmer - I just copied and pasted some existing code. I've added a toggle to the group inspector that if checked will select all children of a group if you click on one of them. It's not particularly elegant, but allows one to select and move around groups without leaving the scene view.
![image](https://user-images.githubusercontent.com/36510916/37440974-7a621e08-27ff-11e8-967b-4d1782c992b6.png)
BrushGroup.cs
```
public class BrushGroup : MonoBehaviour
{
    public bool selectByChild;
}
```
BrushGroupInspector.cs
```
if (GUILayout.Toggle(group.selectByChild, "Select By Child") != group.selectByChild)
{
    group.selectByChild = !group.selectByChild;
}
```
BrushBaseInspector.cs
```
if (BrushTarget.GetComponentInParent<BrushGroup>().selectByChild)
{
    List<Object> objects = Selection.objects.ToList();
    // select all of the child brush objects.
    objects.Remove(BrushTarget.transform.parent.gameObject);
    foreach (Transform child in BrushTarget.transform.parent.transform)
        if (child.GetComponent<BrushBase>())
            objects.Add(child.gameObject);
    Selection.objects = objects.ToArray();
}
```

**Comment by Henry00IS** [comment]
Sorry about the delay, your idea isn't bad and it works quite well but I found another solution that's even better. Now by default the group will be selected (similarly to a compound brush) and you get the common bounds tools. It's even more user friendly and makes the hierarchy selection less awkward.

**Comment by gildedhipbone** [comment]
Awesome! Can't wait to check it out.

**Comment by gildedhipbone** [comment]
Maybe it's a problem on my end, but creating a group will turn subtract brushes into add brushes. This also happens if I attempt to move the group.

**Comment by Henry00IS** [comment]
I can confirm this behavior, nice find. I will have a look and see why this is happening.

**Comment by Henry00IS** [comment]
The issue has been fixed, please try it out. :)

**Comment by Henry00IS** [comment]
Please have another look at the [latest pull request](https://github.com/sabresaurus/SabreCSG/pull/59) update. I removed the 'Always Select Group' flag and it now behaves absolutely amazing just like compound brushes. No more flickering in the hierarchy. You can manually select a child brush in the hierarchy to edit it and if you click in the scene view it will select the whole group. Complete with new inspector icon.

This is the type of behavior that would make @sabresaurus proud. 😁

**Comment by gildedhipbone** [comment]
Wow, that's great work! However, if you move or resize a child, it seems that the group bounds aren't updated automatically.

It's great being able to select a child in the hierarchy without activating the whole group. On that note, I think that it'd be intuitive if this behavior was also reflected in the scene view. Perhaps the user could select a child in the scene view by double-clicking it?

I'm curious - is this way of grouping brushes paving the way to being able to perform CSG operations on groups?

**Comment by Henry00IS** [comment]
Yeah I got stuck with the bounding box size earlier today and I couldn't find a good way to update it but all of the sudden I realized there was an obvious solution all along so it's solved now. Thanks for the reminder.

Double click has been implemented as suggested, feel free to give it a try.

Also not sure what you mean with CSG operations on groups?

**Comment by gildedhipbone** [comment]
You've done it! 👍 The bounding box updates without issue and the double-click selection works perfect.

By CSG operations on groups I mean setting a group to add/subtract (and intersect down the line, perhaps?) like you would an individual brush. Say you have a group consisting of two boxes, one smaller subtracting the other, creating a frame. Settings the group to subtract would essentially give the user a subtracting frame.

**Comment by Henry00IS** [comment]
Ah right! It's literally Unreal Editor's Intersect feature:

![intersect](https://user-images.githubusercontent.com/7905726/37560408-a434a2a2-2a37-11e8-9213-6627f8a38153.gif)

Unless @sabresaurus knows a trick this may not be possible because the new shape is no longer convex (SabreCSG does not support concave shapes, yet).

**Comment by gildedhipbone** [comment]
I've never used EU, but that may well be the kind of feature I had in mind. But I figured I might as well give another example, just for clarity's sake.

![image](https://user-images.githubusercontent.com/36510916/37880783-e8a2ecc6-308d-11e8-8735-a1cd07a810d4.png)
I have this L-shaped brush. As you can see, I created it by subtracting one brush with another. I've grouped the two brushes and I'd like to be able to treat them as a single brush.

In this case I'd like to use this particular group to subtract L-shaped holes in a wall - in other words, I'd like to be able to set the group to subtract, I guess essentially "inverting" the childrens' current mode (while hiding this from the user!).
![image](https://user-images.githubusercontent.com/36510916/37880910-0378a0fc-3090-11e8-8312-c61130698c1d.png)

![image](https://user-images.githubusercontent.com/36510916/37880878-82fd635e-308f-11e8-9240-747b314eda6e.png)

**Comment by Henry00IS** [comment]
Your request should probably be copy & pasted into a new issue.
