### ISSUE TITLE
Weird wireframe behavior based on far away brush

### ISSUE THREAD

**Issue by TheLogan** [sabresaurus/SabreCSG#6]
So I just downloaded SabreCSG like half an hour ago and started playing around. It's been many years since I've used a level editor so it's kind of fun to relearn it.

Anyway I came across an odd issue, this is a screenshot of some mesh in a 'doorway'.

![image](https://cloud.githubusercontent.com/assets/759433/23861864/a309652e-080b-11e7-9fbf-39afdabec424.png)

The black triangle is caused by overlapping faces from what I can surmise. This is the wireframe

![image](https://cloud.githubusercontent.com/assets/759433/23861961/fd0478fc-080b-11e7-8b69-a1165997e6a3.png)

The wall/corridor intersect is crated by having a large box with 2 smaller boxes. This is the entire end wall in wireframe

![image](https://cloud.githubusercontent.com/assets/759433/23862023/2f6f9a74-080c-11e7-83a6-b2346956989c.png)

I was very confused by the circular wireframe until it struck me that it may be defined by a brush that's no where near it, and that turned out to be true.
In the following screenshot I've moved the camera back even further so it's as sort looking into the room it was inside before.

![image](https://cloud.githubusercontent.com/assets/759433/23862126/83f98050-080c-11e7-9461-bba2ecc57dc1.png)

![image](https://cloud.githubusercontent.com/assets/759433/23862107/738f40ba-080c-11e7-8a87-4107c8bf5c39.png)

As you can see the circular wireframe makes sense for this doorway but for some reason the same structure is repeated on the next wall.
To clarify, I'm hollowing out a large cube to create an interior scene, this may be why it's acting out..?
Cause the same pattern is repeated on the wall at the very front of the cube as well even though that's it's even further away from the cyllindrical remove brush.

![image](https://cloud.githubusercontent.com/assets/759433/23862287/ddde2b98-080c-11e7-80ce-8ce8fbfeb06f.png)

I'd be happy to upload the scene too if that's necessary.

**Comment by sabresaurus** [comment]
Can you confirm which version of SabreCSG you're on and also if you have the CSG Model Optimize Geometry flag set

**Comment by TheLogan** [comment]
Certainly.
The changelog says 1.4.0, and so does the asset store.

However I really can't find the 'Model Optimize Geometry' flag.
I figured it would be on the "CSGModel" gameobject? This is all I see.
![image](https://cloud.githubusercontent.com/assets/759433/23926689/e076950c-0915-11e7-8313-b1c857aac437.png)

**Comment by sabresaurus** [comment]
SabreCSG is now maintained on Github, you can download the latest version of it [here](https://github.com/sabresaurus/SabreCSG)

**Comment by TheLogan** [comment]
Ah, ok. I thought it was updated on the asset store too! :)
