### ISSUE TITLE
[Request] Choice to manually set pivot for revolve tool

### ISSUE THREAD

**Issue by Chabinka** [sabresaurus/SabreCSG#69]
It would allow more control over the size of each segment & overall curve of the final result.  I quickly slapped in a field to demonstrate, see here:
https://streamable.com/n5vyt

**Comment by Henry00IS** [comment]
You prefer a textbox over just moving the green pivot further left and right of the shape, correct?

![image](https://user-images.githubusercontent.com/7905726/37849226-253dcdb2-2ed7-11e8-97cb-81ef5e4c881f.png)

I mean I guess it makes sense if you have a super large revolved shape that spans the entire level. It would be a challenge to manually move the pivot so far away of the shape on the grid.

**Comment by Henry00IS** [comment]
I am just asking because in the demo project I sent you it's quite far on the right, perhaps you didn't notice it. :)

![image](https://user-images.githubusercontent.com/7905726/37849944-d65681d2-2ed9-11e8-9ec6-e0a57584379a.png)

**Comment by Chabinka** [comment]
Ahhh no I didn't notice that lol, that's the exact behavior I was after.  I tinkered with it a little, working with larger scale is definitely a bit difficult, I think the input field would be nice to have anyways just for easily setting exact values.  Not a big deal though :)
