### ISSUE TITLE
ShapeEditorWindow.cs error

### ISSUE THREAD

**Issue by zabbarian** [sabresaurus/SabreCSG#80]
Hi.

I put the SabreCSG-master zip file content into assets folder and i am getting following errors. There is no sabrecsg object in the GameObject menu. I tested with Unity 5.6.5f1 and 2017.1.2f1.

Assets/SabreCSG-master/Scripts/Brushes/CompoundBrushes/Editor/ShapeEditorWindow.cs(990,49): error CS0117: `UnityEngine.Screen' does not contain a definition for `safeArea'

Assets/SabreCSG-master/Scripts/Brushes/CompoundBrushes/Editor/ShapeEditorWindow.cs(990,113): error CS0117: `UnityEngine.Screen' does not contain a definition for `safeArea'

Assets/SabreCSG-master/Scripts/Brushes/CompoundBrushes/Editor/ShapeEditorWindow.cs(1350,40): error CS0117: `UnityEngine.Screen' does not contain a definition for `safeArea'

Assets/SabreCSG-master/Scripts/Brushes/CompoundBrushes/Editor/ShapeEditorWindow.cs(1480,47): error CS0117: `UnityEngine.Screen' does not contain a definition for `safeArea'

Assets/SabreCSG-master/Scripts/Brushes/CompoundBrushes/Editor/ShapeEditorWindow.cs(1480,131): error CS0117: `UnityEngine.Screen' does not contain a definition for `safeArea'

**Comment by Henry00IS** [comment]
Hey Zabbarian,

the latest version using the Download Zip option or one of the releases?

![image](https://user-images.githubusercontent.com/7905726/38191399-d9e5d884-3668-11e8-98b4-62346cbbf8e2.png)

v1.6.1, or the latest master, should have already fixed those errors... I am going to double check to make sure.

**Comment by Henry00IS** [comment]
Sorry it seems there is indeed a problem with those Unity versions. I will let you know when it's fixed. May take me a couple minutes.

**Comment by Henry00IS** [comment]
Please [try this version](https://github.com/sabresaurus/SabreCSG/archive/SafeArea.zip) and let me know if it works properly. :)

**Comment by zabbarian** [comment]
Hi Henry.

I just tested last version you put with both Unity 5.6.5f1 and 2017.1.2f1. It's working fine now with no errors. I can see the "Create CSG" object in the GameObject menu. Thanks.

**Comment by Henry00IS** [comment]
Thank you so much, that was one of the most important findings yet as it broke all versions of Unity between 5.3 and 2017.2. Thanks again! 😁
