### ISSUE TITLE
Add a button to fix the shiny matte ugliness.

### ISSUE THREAD

**Issue by Henry00IS** [sabresaurus/SabreCSG#82]
You often get this very ugly matte shine:

![image](https://user-images.githubusercontent.com/7905726/38194455-e598517a-3677-11e8-8c80-5b2b68047028.png)

The problem is the reflection probe, making the reflection probe black will cause all metals to be black which is not what you want, in the "MaterialMesh" settings you can disable reflection probes:

![image](https://user-images.githubusercontent.com/7905726/38194516-3f2ef7ca-3678-11e8-8bea-26b463ebc117.png)

To get the result you'd want:

![image](https://user-images.githubusercontent.com/7905726/38194489-194b7646-3678-11e8-816a-ea267cd0dd0c.png)

But SabreCSG forgets this setting after every rebuild. Perhaps this should be the default- or have a checkbox in the CSG Model settings that's like:

**Common Fixes**
[  ] The world is shiny and weird

As I am not sure everyone will immediately realize it's the reflection probe causing this, like me, and even exposing the reflection probe settings in the CSG Model may then not help anyone figure it out at first.

**Comment by vertxxyz** [comment]
You need Reflection Probes to have functional reflections, it's not a
SabreCSG problem. SabreCSG should probably reuse the settings found on
previous MeshRenderers with the same material type - but that should be the
case regardless of this setting.
